spring:
  redis:
#    host: 127.0.0.1
#    port: 8001
    password: scope2019
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 100
        min-idle: 50
        max-wait: 3000
        shutdown-timeout: 100
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:28001,127.0.0.1:28002,127.0.0.1:28003